### ISSUE TITLE
User should be able to choose deletion method

### ISSUE THREAD

**Issue by Albirew** [DevelopersTree/permadelete#32]
Right now, user doesn't have any choice for deletion method.
App should have an option so user can choose preferred deletion method from a list:
- Gutmann (35 passes)
- AR 380-19 (3 passes)
- RCMP TSSIT OPS-II (7 passes)
- etc.

You can find a more complete list with deletion details on [this webpage](https://www.lifewire.com/data-sanitization-methods-2626133)

**Comment by encrypt0r** [comment]
You're right, this feature is very important. I have a few settings (including this one) I'd like to add for Permadelete. However, these days I rarely have time to work on it. I'd happily accept a PR though. Otherwise, it would wait until I get the chance to work on it.

**Comment by encrypt0r** [comment]
resolved by #37
