### ISSUE TITLE
Being able to change Permadelete's theme color

### ISSUE THREAD

**Issue by encrypt0r** [DevelopersTree/permadelete#33]
Some folks might not like the default color of Permadelete, especially if they work in enterprise environments. Having the option to change the theme color would be nice

**Comment by rasyidf** [comment]
PermaDelete Is Great, but the theme is bad (Low Extensibility).

i've created permadelete ui with MetroStyle, for some inspiration.

the original style,  purple

![permadel 3](https://user-images.githubusercontent.com/28984914/50854543-ee54f980-13b7-11e9-98e7-2b81ced3f05c.jpg)


and this is blue.
![permadel](https://user-images.githubusercontent.com/28984914/50854540-ee54f980-13b7-11e9-82e3-845135942db7.jpg)

then my fav color
![permadel 2](https://user-images.githubusercontent.com/28984914/50854544-ee54f980-13b7-11e9-886a-e689d4e48c4c.jpg)

What's your opinion on that? @encrypt0r

**Comment by encrypt0r** [comment]
@rasyidf All of the colors are defined in [Style.xaml](https://github.com/DevelopersTree/permadelete/blob/master/Permadelete.FrontEnd/Styles.xaml#L25) and we can use `DynamicResource` instead of `StaticResource` to change the color at runtime. So I don't think to change the entire UI.

**Comment by encrypt0r** [comment]
resloved by #38
