### ISSUE TITLE
Install the file with administrator privileges, still can't delete it

### ISSUE THREAD

**Issue by Jon123468964** [DevelopersTree/permadelete#48]
![52436F52-3CCE-4B60-9C64-5438A11C74F9](https://user-images.githubusercontent.com/115492977/194919940-72f7c39b-7813-4045-b815-428a14604c94.jpeg)

**Comment by Jon123468964** [comment]
help me…

**Comment by Jon123468964** [comment]
I have installed Permadelete with admin rights and still can't delete the file.  Files can only be deleted to the Recycle Bin, you cannot delete files using Permadelete.

**Comment by mhmd-azeez** [comment]
You need to run Permadelete as administrator, please take a look at this article:
https://www.windowscentral.com/how-run-app-administrator-windows-10
