### ISSUE TITLE
Can't use Permadelete, can only delete files to the recycle bin, my system is windows7。

### ISSUE THREAD

**Issue by Jon123468964** [DevelopersTree/permadelete#50]
How to get administrator rights in windows 7?  I have tried many ways and have failed without exception.
![Uploading 74D4A178-10D4-4E07-8E05-35717CF123A9.jpeg…]()

**Comment by Jon123468964** [comment]
![Uploading A5E6A4B9-5772-4A77-A10E-40923B3D4D6F.jpeg…]()

**Comment by Jon123468964** [comment]
![image](https://user-images.githubusercontent.com/115492977/195437145-7d3125f3-91b1-438f-bb2c-36332a088a38.jpeg)

**Comment by Jon123468964** [comment]
I'm really pissed off by this OS 😡

**Comment by Jon123468964** [comment]
The software is very easy to use, but I'm a noob

**Comment by mhmd-azeez** [comment]
Please stop spamming the repo. Duplicate of #49
